import './globals.css';
import TopNav from './TopNav';
import SideBar from './SideBar';

export const metadata = {
  title: 'Reddit Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-950 text-zinc-50">
        <div className="flex flex-col h-screen">
          <TopNav />
          <div className="flex flex-1 pt-12">
            <SideBar />
            <div className="flex-1">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
